export enum Genre {
  Fiction = 'Fiction',
  ScienceFiction = 'Science Fiction',
  Mystery = 'Mystery',
  Romance = 'Romance',
  NonFiction = 'Non-Fiction',
  Fantasy = 'Fantasy',
  Biography = 'Biography',
  History = 'History',
  Thriller = 'Thriller',
  YoungAdult = 'Young Adult',
  Horror = 'Horror',
  Poetry = 'Poetry',
  SelfImprovement = 'Self Improvement',
  Adventure = 'Adventure',
  Drama = 'Drama',
  Comedy = 'Comedy',
  Action = 'Action',
  Crime = 'Crime',
  Gothic = 'Gothic',
  Epic = 'Epic',
  CrimeFiction = 'Crime Fiction',
}

export const GENRE_OPTIONS: string[] = Object.values(Genre);
